/*
 * RetroNet Get (RGET) v0.2 by GTAMP (c) 2026
 * Prompts and testing by GTAMP
 * Code generated by Gemini 3 Flash (free)
 */

#define BIN_TYPE BIN_CPM
#define DISABLE_VDP 
#define DISABLE_KEYBOARD_INT

#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include "../../NABULIB/RetroNET-FileStore.h"
#include "../../NABULIB/NABU-LIB.h"
#include <string.h>
#include <ctype.h>

#define CPM_CMD_LEN  (*(uint8_t *)0x0080)
#define CPM_CMD_TEXT ((char *)0x0081)
#define BUFFERSIZE 128

/* Buffers */
uint8_t _buffer[BUFFERSIZE];
uint8_t bdosBuffer[130]; 
char rawUrl[128];
char rawFile[128];
char pathPart[128];
char wildPart[32];
char fullRemote[160];
uint32_t _totalBytesDownloaded = 0;

/* --- Helpers --- */

void safeExit() {
  __asm
    ei
    jp 0x0000
  __endasm;
}

void showHelp() {
    printf("\nUsage: RGET [URL] [filename]\n\n");
    printf("Examples:\n");
    printf("RGET gtamp.com/nabu/vgmp.com v.com\n");
    printf("RGET gtamp.com/nabu/oilswell.com\n");
    printf("RGET ia: (list directory)\n");
    printf("RGET ia:vgm/*.vgm (batch download)\n");
    printf("RGET /U (Update RGET from gtamp.com)\n");
    printf("RGET (no args for mixed case URL)\n");
    safeExit();
}

uint8_t fileExists(const char *name) {
    FILE *f = fopen(name, "rb");
    if (f) { fclose(f); return 1; }
    return 0;
}

void abortProg(uint8_t h, FILE *f, const char *msg) {
  if (h != 0xff) rn_fileHandleClose(h);
  if (f != NULL) fclose(f);
  printf("\n%s\n", msg);
  safeExit();
}

uint8_t isMatch(char* s1, char* s2) {
    while (*s1 && *s2) {
        if (toupper((uint8_t)*s1) != toupper((uint8_t)*s2)) return 0;
        s1++; s2++;
    }
    return (toupper((uint8_t)*s1) == toupper((uint8_t)*s2));
}

void getLine(char* dest, uint8_t maxLen) {
  bdosBuffer[0] = maxLen; bdosBuffer[1] = 0;
  __asm
    ld de, #_bdosBuffer
    ld c, #10
    call 5
  __endasm;
  uint8_t len = bdosBuffer[1]; 
  memcpy(dest, &bdosBuffer[2], len); 
  dest[len] = '\0';
  printf("\n"); 
}

/* --- Remote Storage Support --- */

uint8_t iaFileExists(char* fullPath) {
    char parent[128], target[32];
    FileDetailsStruct entry;
    uint16_t count, i;
    char *ptr = strrchr(fullPath, '\\');
    if (!ptr) ptr = strrchr(fullPath, '/');
    if (!ptr) { strcpy(parent, "\\"); strcpy(target, fullPath); }
    else {
        int pos = (int)(ptr - fullPath);
        strncpy(parent, fullPath, (size_t)pos); parent[pos] = '\0';
        strcpy(target, ptr + 1);
    }
    if (parent[0] == '\0') strcpy(parent, "\\");
    count = rn_fileList((uint8_t)strlen(parent), parent, (uint8_t)strlen(target), target, FILE_LIST_FLAG_INCLUDE_FILES);
    for (i = 0; i < count; i++) {
        rn_fileListItem(i, &entry);
        if (isMatch(entry.Filename, target) && entry.IsFile) return 1;
    }
    return 0;
}

void doDirectory(char* path) {
    uint16_t count, i;
    FileDetailsStruct entry;
    char* searchPath = path + 3; 
    char cleanPath[128];
    strcpy(cleanPath, searchPath);
    i = (uint16_t)strlen(cleanPath);
    if (i > 1 && (cleanPath[i-1] == '\\' || cleanPath[i-1] == '/')) cleanPath[i-1] = '\0';
    if (cleanPath[0] == '\0') strcpy(cleanPath, "\\");

    printf("Listing: %s\n", cleanPath);
    count = rn_fileList((uint8_t)strlen(cleanPath), cleanPath, 3, "*.*", 
                      FILE_LIST_FLAG_INCLUDE_FILES | FILE_LIST_FLAG_INCLUDE_DIRECTORIES);
    for (i = 0; i < count; i++) {
        rn_fileListItem(i, &entry);
        if (entry.IsFile) printf("%-12s  %ld bytes\n", entry.Filename, entry.FileSize);
        else printf("[%s]\n", entry.Filename);
    }
    printf("\n%u item(s).\n", count);
}

uint8_t isIAFolder(char* input) {
    char parent[128], target[32];
    FileDetailsStruct entry;
    uint16_t count, i;
    char *path = input + 3; 
    char *ptr = strrchr(path, '\\');
    if (!ptr) ptr = strrchr(path, '/');
    if (!ptr) { strcpy(parent, "\\"); strcpy(target, path); }
    else {
        int pos = (int)(ptr - path);
        strncpy(parent, path, (size_t)pos); parent[pos] = '\0';
        strcpy(target, ptr + 1);
    }
    if (parent[0] == '\0') strcpy(parent, "\\");
    if (target[0] == '\0') return 1;
    count = rn_fileList((uint8_t)strlen(parent), parent, (uint8_t)strlen(target), target, 
                       FILE_LIST_FLAG_INCLUDE_FILES | FILE_LIST_FLAG_INCLUDE_DIRECTORIES);
    for (i = 0; i < count; i++) {
        rn_fileListItem(i, &entry);
        if (isMatch(entry.Filename, target)) return !entry.IsFile;
    }
    return 0;
}

/* --- Download Core --- */

uint8_t downloadFile(const char* path, const char* localName) {
    uint8_t handle = 0xff;
    uint16_t readBytes = 0;
    uint32_t currentFileBytes = 0;
    uint8_t pct = 0, barChars = 0, i;
    FileDetailsStruct details;
    FILE *fp = NULL;

    handle = rn_fileOpen((uint8_t)strlen(path), (char*)path, OPEN_FILE_FLAG_READONLY, 0xff);
    if (handle == 0xff) { printf("Error: 404 Not Found\n"); return 0; }

    rn_fileHandleDetails(handle, &details);
    if (!details.IsFile) { 
        printf("Error: Bad URL or file.\n");
        rn_fileHandleClose(handle); return 0; 
    }

    printf("File: %-12s (%ld bytes)\n", localName, details.FileSize);
    fp = fopen(localName, "wb");
    if (!fp) { rn_fileHandleClose(handle); printf("Error: Disk Write Error\n"); return 0; }

    while (1) {
        if (kbhit() && getch() == 0x03) abortProg(handle, fp, "ABORTED");
        readBytes = rn_fileHandleReadSeq(handle, _buffer, 0, BUFFERSIZE);
        if (readBytes == 0) break; 
        if (fwrite(_buffer, 1, readBytes, fp) != readBytes) {
           fclose(fp); remove(localName); rn_fileHandleClose(handle);
           printf("\nError: Disk Full!\n"); return 0;
        }
        currentFileBytes += (uint32_t)readBytes;
        _totalBytesDownloaded += (uint32_t)readBytes;

        if (details.FileSize > 0 && ((currentFileBytes & 0x03FF) == 0 || currentFileBytes == details.FileSize)) {
            pct = (uint8_t)((currentFileBytes * 100) / details.FileSize);
            barChars = pct / 10;
            printf("\r[");
            for(i = 0; i < 10; i++) {
                if (i < barChars) { if (i == barChars - 1 && i < 9) putchar('>'); else putchar('='); }
                else putchar(' ');
            }
            printf("] %3u%% %ldb", pct, currentFileBytes);
        }
    }
    fclose(fp);
    rn_fileHandleClose(handle);
    printf("\r[==========] 100%% - OK                      \n\n");
    return 1;
}

/* --- Main Loop --- */

void main() {
    FileDetailsStruct entry;
    uint16_t i, k, count;
    char finalUrl[160];
    char finalLocal[16];
    char tempFile[128];
    uint8_t yn;

    printf("RetroNet Get v0.2 by GTAMP (c) 2026\n");
    printf("Type RGET /? for help\n\n");

    rawUrl[0] = '\0'; rawFile[0] = '\0';

    /* Parse Command Line Tail */
    if (CPM_CMD_LEN > 0) {
        i = 0;
        while (i < CPM_CMD_LEN && (uint8_t)CPM_CMD_TEXT[i] <= 32) i++;
        k = 0;
        while (i < CPM_CMD_LEN && (uint8_t)CPM_CMD_TEXT[i] > 32) {
            rawUrl[k++] = (char)tolower((uint8_t)CPM_CMD_TEXT[i++]);
        }
        rawUrl[k] = '\0';
        while (i < CPM_CMD_LEN && (uint8_t)CPM_CMD_TEXT[i] <= 32) i++;
        k = 0;
        while (i < CPM_CMD_LEN && (uint8_t)CPM_CMD_TEXT[i] > 32) {
            rawFile[k++] = (char)toupper((uint8_t)CPM_CMD_TEXT[i++]);
        }
        rawFile[k] = '\0';
    }

    if (strcmp(rawUrl, "/?") == 0 || strcmp(rawUrl, "help") == 0) showHelp();
    
    if (strcmp(rawUrl, "/u") == 0) {
        printf("Updating RGET...\n");
        downloadFile("https://gtamp.com/nabu/rget.com", "RGET.COM");
        safeExit();
    }

    /* Prompt if no URL provided */
    if (rawUrl[0] == '\0') { 
        printf("URL: "); 
        getLine(rawUrl, 127); 
        
        char *spacePtr = strchr(rawUrl, ' ');
        if (spacePtr) {
            *spacePtr = '\0';
            strcpy(rawFile, spacePtr + 1);
            char *fs = rawFile;
            while (*fs == ' ') fs++;
            if (fs != rawFile) memmove(rawFile, fs, strlen(fs) + 1);
        }
        for(i=0; rawUrl[i] != '\0'; i++) rawUrl[i] = (char)tolower((uint8_t)rawUrl[i]);
    }
    if (rawUrl[0] == '\0') safeExit();

    /* IA Protocol Logic */
    if (strncmp(rawUrl, "ia:", 3) == 0) {
        if (isIAFolder(rawUrl)) { doDirectory(rawUrl); safeExit(); }
        if (strchr(rawUrl, '*') || strchr(rawUrl, '?')) {
            char *ptr = strrchr(rawUrl, '\\');
            if (!ptr) ptr = strrchr(rawUrl, '/');
            if (!ptr) { strcpy(pathPart, "\\"); strcpy(wildPart, rawUrl + 3); }
            else {
                int pos = (int)(ptr - rawUrl);
                strncpy(pathPart, rawUrl + 3, (size_t)(pos - 3)); pathPart[pos - 3] = '\0';
                strcpy(wildPart, ptr + 1);
            }
            if (pathPart[0] == '\0') strcpy(pathPart, "\\");
            count = rn_fileList((uint8_t)strlen(pathPart), pathPart, (uint8_t)strlen(wildPart), wildPart, FILE_LIST_FLAG_INCLUDE_FILES);
            if (count > 0) {
                printf("Download %u files (Y/N)? ", count);
                yn = (uint8_t)toupper(getch()); printf("%c\n\n", yn);
                if (yn != 'Y') safeExit();
                for (i = 0; i < count; i++) {
                    rn_fileListItem(i, &entry);
                    if (entry.IsFile) {
                        if (fileExists(entry.Filename)) { printf("Skipping %s\n", entry.Filename); continue; }
                        strcpy(fullRemote, pathPart);
                        if (fullRemote[strlen(fullRemote)-1] != '\\') strcat(fullRemote, "\\");
                        strcat(fullRemote, entry.Filename);
                        downloadFile(fullRemote, entry.Filename);
                    }
                }
            } else printf("Error: No matching files found.\n");
            safeExit();
        }
    }

    /* URL Normalization */
    if (strncmp(rawUrl, "ia:", 3) != 0 && strncmp(rawUrl, "http", 4) != 0 && strncmp(rawUrl, "ftp:", 4) != 0) {
        strcpy(finalUrl, "https://"); strcat(finalUrl, rawUrl);
    } else {
        strcpy(finalUrl, (strncmp(rawUrl, "ia:", 3) == 0) ? rawUrl + 3 : rawUrl);
    }

    /* Target Filename Sanitizer */
    char *baseName;
    if (rawFile[0] != '\0') {
        strcpy(tempFile, rawFile);
        baseName = strrchr(tempFile, '/');
        if (!baseName) baseName = strrchr(tempFile, '\\');
        baseName = (baseName) ? baseName + 1 : tempFile;
    } else {
        char *ptr = finalUrl;
        while (*ptr == '/' || *ptr == '\\') ptr++;
        baseName = strrchr(ptr, '/');
        if (!baseName) baseName = strrchr(ptr, '\\');
        baseName = (baseName) ? baseName + 1 : ptr;
        if (baseName[0] == '\0' || (ptr == finalUrl && !strchr(ptr, '/'))) baseName = "OUT.BIN";
    }

    /* Force 8.3 and Uppercase */
    strncpy(finalLocal, baseName, 12); finalLocal[12] = '\0';
    for(i=0; i<strlen(finalLocal); i++) finalLocal[i] = (char)toupper((uint8_t)finalLocal[i]);

    printf("Saving as: %s\n", finalLocal);

    if (fileExists(finalLocal)) {
        printf("%s exists. Overwrite (Y/N)? ", finalLocal);
        yn = (uint8_t)toupper(getch()); printf("%c\n", yn);
        if (yn != 'Y') safeExit();
    }

    downloadFile(finalUrl, finalLocal);
    safeExit();
}
